# Generated by Django 5.0.6 on 2024-06-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_onlinebooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebooking',
            name='service',
            field=models.CharField(max_length=300),
        ),
    ]
